batch_size: 256
clip_gradient_norm: 1
clip_targets_to_zero:
- QObs(mm/d)
commit_hash: a27a174
conceptual_model: shm
conceptual_param_config: oracle_average
custom_normalization:
  QObs(mm/d):
    centering: None
    scaling: None
  PRCP(mm/day)_nldas_copy1:
    centering: None
    scaling: None
  srad(W/m2)_daymet_copy1:
    centering: None
    scaling: None
  tmin(C)_daymet_copy1:
    centering: None
    scaling: None
  tmax(C)_daymet_copy1:
    centering: None
    scaling: None
data_dir: /home/adam/dev/repos/neuralhydrology-dcfe/data/CAMELS_US
dataset: camels_us
device: cpu
duplicate_features:
- PRCP(mm/day)_nldas
- tmax(C)_daymet
- tmin(C)_daymet
- srad(W/m2)_daymet
dynamic_conceptual_inputs:
- PRCP(mm/day)_nldas_copy1
- tmin(C)_daymet_copy1
- tmax(C)_daymet_copy1
- srad(W/m2)_daymet_copy1
dynamic_inputs:
- PRCP(mm/day)_nldas
- PRCP(mm/day)_maurer
- prcp(mm/day)_daymet
- srad(W/m2)_daymet
- tmax(C)_daymet
- tmin(C)_daymet
- vp(Pa)_daymet
epochs: 10
experiment_name: example_SHM_oracle_average
forcings:
- maurer
- daymet
- nldas
head: regression
hidden_size: 20
img_log_dir: 
  /home/adam/dev/repos/neuralhydrology-dcfe/examples/08-SHM/runs/example_SHM_oracle_average_1104_090622/img_log
initial_forget_bias: 3
learning_rate:
  0: 0.05
  20: 0.001
  40: 1e-05
log_interval: 5
log_n_figures: 1
log_tensorboard: true
loss: MSE
metrics:
- NSE
model: hybrid_model
num_workers: 8
number_of_basins: 2
optimizer: Adam
output_activation: linear
output_dropout: 0.2
package_version: 1.12.0
predict_last_n: 365
run_dir: 
  /home/adam/dev/repos/neuralhydrology-dcfe/examples/08-SHM/runs/example_SHM_oracle_average_1104_090622
save_all_output: true
save_weights_every: 1
seed: 123
seq_length: 910
spin_up_period: 365
target_variables:
- QObs(mm/d)
test_basin_file: /home/adam/dev/repos/neuralhydrology-dcfe/examples/08-SHM/2_basin.txt
test_end_date: 30/09/2004
test_start_date: 01/10/1999
train_basin_file: /home/adam/dev/repos/neuralhydrology-dcfe/examples/08-SHM/2_basin.txt
train_dir: 
  /home/adam/dev/repos/neuralhydrology-dcfe/examples/08-SHM/runs/example_SHM_oracle_average_1104_090622/train_data
train_end_date: 30/09/2014
train_start_date: 01/10/2000
validate_every: 2
validate_n_random_basins: 1
validation_basin_file: /home/adam/dev/repos/neuralhydrology-dcfe/examples/08-SHM/2_basin.txt
validation_end_date: 30/09/1999
validation_start_date: 01/10/1990
warmup_period: 180
