xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    PRCP(mm/day)_maurer:
      dims: []
      attrs: {}
      data: 7.982968807220459
    PRCP(mm/day)_nldas:
      dims: []
      attrs: {}
      data: 9.987279891967773
    PRCP(mm/day)_nldas_copy1:
      dims: []
      attrs: {}
      data: 1.0
    QObs(mm/d):
      dims: []
      attrs: {}
      data: 1.0
    prcp(mm/day)_daymet:
      dims: []
      attrs: {}
      data: 10.291688919067383
    srad(W/m2)_daymet:
      dims: []
      attrs: {}
      data: 104.87727355957031
    srad(W/m2)_daymet_copy1:
      dims: []
      attrs: {}
      data: 1.0
    tmax(C)_daymet:
      dims: []
      attrs: {}
      data: 8.270487785339355
    tmax(C)_daymet_copy1:
      dims: []
      attrs: {}
      data: 1.0
    tmin(C)_daymet:
      dims: []
      attrs: {}
      data: 8.617350578308105
    tmin(C)_daymet_copy1:
      dims: []
      attrs: {}
      data: 1.0
    vp(Pa)_daymet:
      dims: []
      attrs: {}
      data: 689.2484741210938
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    PRCP(mm/day)_maurer:
      dims: []
      attrs: {}
      data: 3.8366379737854004
    PRCP(mm/day)_nldas:
      dims: []
      attrs: {}
      data: 3.861855983734131
    PRCP(mm/day)_nldas_copy1:
      dims: []
      attrs: {}
      data: 0.0
    QObs(mm/d):
      dims: []
      attrs: {}
      data: 0.0
    prcp(mm/day)_daymet:
      dims: []
      attrs: {}
      data: 4.265314102172852
    srad(W/m2)_daymet:
      dims: []
      attrs: {}
      data: 350.2944641113281
    srad(W/m2)_daymet_copy1:
      dims: []
      attrs: {}
      data: 0.0
    tmax(C)_daymet:
      dims: []
      attrs: {}
      data: 22.15067481994629
    tmax(C)_daymet_copy1:
      dims: []
      attrs: {}
      data: 0.0
    tmin(C)_daymet:
      dims: []
      attrs: {}
      data: 9.372939109802246
    tmin(C)_daymet_copy1:
      dims: []
      attrs: {}
      data: 0.0
    vp(Pa)_daymet:
      dims: []
      attrs: {}
      data: 1338.363037109375
